/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Gibi' at '5/10/16 11:10 AM' with Gradle 2.9
 *
 * @author Gibi, @date 5/10/16 11:10 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
